# Generated by Django 5.0.6 on 2024-05-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedfeed',
            name='update_frequency',
        ),
    ]
