# Generated by Django 5.0.6 on 2024-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0002_remove_processedfeed_update_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='summary_language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('url', 'original_feed')},
        ),
    ]
