# Generated by Django 5.0.6 on 2024-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0004_remove_processedfeed_max_articles_to_process_per_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfeed',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
