# Generated by Django 5.0.6 on 2024-05-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0005_processedfeed_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalfeed',
            name='max_articles_to_keep',
            field=models.PositiveIntegerField(default=1000, help_text='Older articles will be removed when the limit is reached.'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional title for the original feed', max_length=255),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='url',
            field=models.URLField(help_text='URL of the Atom or RSS feed', unique=True),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='additional_prompt',
            field=models.TextField(blank=True, default='', help_text='This prompt will override the default prompt for summarization, you can use it for translation or other detailed instructions.', verbose_name='Custom Prompt'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='articles_to_summarize_per_interval',
            field=models.PositiveIntegerField(default=0, help_text='All articles will be included in the feed, but only the set number of articles will be summarized per update, set to 0 to disable summarization.', verbose_name='Articles to summarize per update'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='feeds',
            field=models.ManyToManyField(help_text='All selected original feeds will be aggregated into this feed.', related_name='processed_feeds', to='FeedManager.originalfeed'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='filter_relational_operator',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', help_text='The included articles must match All/Any/None of the filters.', max_length=20),
        ),
    ]
