# Generated by Django 5.0.6 on 2024-05-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0006_alter_originalfeed_max_articles_to_keep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalfeed',
            name='url',
            field=models.URLField(help_text='URL of the Atom or RSS feed', max_length=2048, unique=True),
        ),
    ]
