# Generated by Django 5.0.6 on 2024-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0007_alter_originalfeed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary_one_line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
