# Generated by Django 5.0.6 on 2024-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0009_article_custom_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfeed',
            name='additional_prompt_for_digest',
            field=models.TextField(blank=True, default='', verbose_name='Custom Prompt for Digest.'),
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency of the digest.', max_length=20),
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='digest_time',
            field=models.TimeField(default='08:00', help_text='Time of day to send the digest.'),
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='send_full_article',
            field=models.BooleanField(default=False, help_text='Send full article content to AI for additional digest, default only sends link, title, and summary.'),
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='toggle_digest',
            field=models.BooleanField(default=False, help_text='Send a daily digest email with the latest articles.'),
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='toggle_entries',
            field=models.BooleanField(default=True, help_text='Include original articles in the feed.'),
        ),
    ]
