# Generated by Django 5.0.6 on 2024-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0011_processedfeed_filter_relational_operator_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfeed',
            name='additional_prompt_for_digest',
            field=models.TextField(blank=True, default='', help_text='Using AI to generate digest, otherwise only the title, link and summary from the database will be included in the digest.', verbose_name='(Optional) Prompt for Digest'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='send_full_article',
            field=models.BooleanField(default=False, help_text='(Ignored without prompt) Send full article content for AI digest, by default only link, title, and summary are sent.'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='toggle_digest',
            field=models.BooleanField(default=False, help_text='Send a digest of the feed regularly.'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='toggle_entries',
            field=models.BooleanField(default=True, help_text='Include entries in the feed, disable to only send digest regularly.'),
        ),
    ]
