# Generated by Django 5.0.6 on 2024-05-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0012_alter_processedfeed_additional_prompt_for_digest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedfeed',
            name='digest_time',
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='last_digest',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='FeedManager.processedfeed')),
            ],
        ),
    ]
