# Generated by Django 5.0.6 on 2024-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0016_processedfeed_digest_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalfeed',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Optional tag for the original feed', max_length=255),
        ),
        migrations.AddField(
            model_name='originalfeed',
            name='valid',
            field=models.BooleanField(blank=True, default=None, editable=False, help_text='Whether the feed is valid.', null=True),
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='include_toc',
            field=models.BooleanField(default=True, help_text='Include table of contents in digest.'),
        ),
    ]
