# Generated by Django 5.0.6 on 2024-05-30 19:59

import django.db.models.deletion
from django.db import migrations, models

def create_filter_groups_for_feeds_with_filters(apps, schema_editor):
    ProcessedFeed = apps.get_model('FeedManager', 'ProcessedFeed')
    FilterGroup = apps.get_model('FeedManager', 'FilterGroup')
    Filter = apps.get_model('FeedManager', 'Filter')

    for feed in ProcessedFeed.objects.all():
        # Check if the current ProcessedFeed has any associated Filters
        if Filter.objects.filter(processed_feed=feed).exists():
            # Create a FilterGroup for the ProcessedFeed
            filter_group = FilterGroup.objects.create(
                processed_feed=feed,
                usage='feed_filter', # hard-code to feed_filter, manually change if necessary
                relational_operator=feed.feed_group_relational_operator,
            )

            # Reassociate each Filter from this ProcessedFeed to the new FilterGroup
            filters = Filter.objects.filter(processed_feed=feed)
            filters.update(filter_group=filter_group)  # Bulk update to set the new filter_group

class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0017_originalfeed_tag_originalfeed_valid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedfeed',
            old_name='filter_relational_operator',
            new_name='feed_group_relational_operator',
        ),
        migrations.RenameField(
            model_name='processedfeed',
            old_name='filter_relational_operator_summary',
            new_name='summary_group_relational_operator',
        ),
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(choices=[('feed_filter', 'Feed Filter'), ('summary_filter', 'Summary Filter')], default='feed_filter', max_length=15)),
                ('relational_operator', models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', max_length=20)),
                ('processed_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_groups', to='FeedManager.processedfeed')),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='filter_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='FeedManager.filtergroup'),
        ),
        migrations.RunPython(create_filter_groups_for_feeds_with_filters),
        migrations.RemoveField(
            model_name='filter',
            name='processed_feed',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='usage',
        ),
    ]
