# Generated by Django 4.2.13 on 2024-05-31 00:20

from django.db import migrations, models
import django.db.models.deletion

def check_filter_group(apps, schema_editor):
    Filter = apps.get_model('FeedManager', 'Filter')
    # Ensure every Filter has a FilterGroup associated
    if Filter.objects.filter(filter_group__isnull=True).exists():
        raise Exception("There are filters without a filter group assigned.")

class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0018_rename_filter_relational_operator_processedfeed_feed_group_relational_operator_and_more'),
    ]

    operations = [
        migrations.RunPython(check_filter_group),
        migrations.AlterField(
            model_name='filter',
            name='filter_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='FeedManager.filtergroup'),
        ),
    ]
