# Generated by Django 5.0.6 on 2024-05-31 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0019_alter_filter_filter_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url',
            new_name='link',
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('link', 'original_feed')},
        ),
    ]
