# Generated by Django 5.0.6 on 2024-07-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0021_tag_remove_originalfeed_tag_originalfeed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfeed',
            name='other_digest_model',
            field=models.CharField(blank=True, default='', help_text="AI Model for digest generation, only used if 'Other' is selected.", max_length=255),
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='other_model',
            field=models.CharField(blank=True, default='', help_text="AI Model for summarization, only used if 'Other' is selected.", max_length=255),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('other', 'Other')], default='gpt-3.5-turbo', help_text='Model for digest generation.', max_length=20),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('other', 'Other')], default='gpt-3.5-turbo', max_length=20),
        ),
    ]
