# Generated by Django 5.0.6 on 2024-07-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0022_processedfeed_other_digest_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('other', 'Other (specify below)')], default='gpt-3.5-turbo', help_text='Model for digest generation.', max_length=20),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('other', 'Other (specify below)')], default='gpt-3.5-turbo', max_length=20),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='other_digest_model',
            field=models.CharField(blank=True, default='', help_text="Please specify the model if 'Other' is selected above, e.g. 'gemini-1.5-pro' in OneAPI.", max_length=255),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='other_model',
            field=models.CharField(blank=True, default='', help_text="Please specify the model if 'Other' is selected above, e.g. 'gemini-1.5-pro' in OneAPI.", max_length=255),
        ),
    ]
