# Generated by Django 5.1.2 on 2024-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FeedManager", "0023_alter_processedfeed_digest_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedfeed",
            name="translate_title",
            field=models.BooleanField(
                default=False,
                help_text="If this options is true, Article title is translated to summary language.",
                verbose_name="Article Title Translation",
            ),
        ),
    ]
