# Generated by Django 5.0.6 on 2024-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0024_processedfeed_translate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='field',
            field=models.CharField(choices=[('title', 'Title'), ('content', 'Content'), ('link', 'Link'), ('title_or_content', 'Title or content')], max_length=20),
        ),
    ]
