# Generated by Django 5.0.6 on 2025-04-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0025_alter_filter_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfeed',
            name='case_sensitive',
            field=models.BooleanField(default=False, help_text='For filter keyword, default to unchecked for ignoring case.'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='other_digest_model',
            field=models.CharField(blank=True, default='', help_text="Please specify the OpenAI-compatible model if 'Other' is selected above, e.g. 'grok-3-beta' in GrokAI or OneAPI.", max_length=255),
        ),
    ]
