# Generated by Django 5.0.6 on 2025-08-18 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0026_processedfeed_case_sensitive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsetting',
            options={'verbose_name': 'App Setting', 'verbose_name_plural': 'App Settings'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='digest',
            options={'verbose_name': 'Digest', 'verbose_name_plural': 'Digests'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'Filter', 'verbose_name_plural': 'Filters'},
        ),
        migrations.AlterModelOptions(
            name='filtergroup',
            options={'verbose_name': 'Filter Group', 'verbose_name_plural': 'Filter Groups'},
        ),
        migrations.AlterModelOptions(
            name='originalfeed',
            options={'verbose_name': 'Original Feed', 'verbose_name_plural': 'Original Feeds'},
        ),
        migrations.AlterModelOptions(
            name='processedfeed',
            options={'verbose_name': 'Processed Feed', 'verbose_name_plural': 'Processed Feeds'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='auth_code',
            field=models.CharField(blank=True, help_text='Optional authentication code required to access RSS feeds.', max_length=64, null=True, verbose_name='Auth Code'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='custom_prompt',
            field=models.BooleanField(default=False, verbose_name='Custom Prompt Used'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='original_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='FeedManager.originalfeed', verbose_name='Original Feed'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summarized',
            field=models.BooleanField(default=False, verbose_name='Summarized'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary_one_line',
            field=models.TextField(blank=True, null=True, verbose_name='One Line Summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='processed_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='FeedManager.processedfeed', verbose_name='Processed Feed'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='field',
            field=models.CharField(choices=[('title', 'Title'), ('content', 'Content'), ('link', 'Link'), ('title_or_content', 'Title or content')], max_length=20, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='filter_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='FeedManager.filtergroup', verbose_name='Filter Group'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='match_type',
            field=models.CharField(choices=[('contains', 'Contains'), ('does_not_contain', 'Does not contain'), ('matches_regex', 'Matches regex'), ('does_not_match_regex', 'Does not match regex'), ('shorter_than', 'Shorter than'), ('longer_than', 'Longer than')], max_length=20, verbose_name='Match Type'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='processed_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_groups', to='FeedManager.processedfeed', verbose_name='Processed Feed'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='relational_operator',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', max_length=20, verbose_name='Relational Operator'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='usage',
            field=models.CharField(choices=[('feed_filter', 'Feed Filter'), ('summary_filter', 'Summary Filter')], default='feed_filter', max_length=15, verbose_name='Usage'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='max_articles_to_keep',
            field=models.PositiveIntegerField(default=1000, help_text='Older articles will be removed when the limit is reached.', verbose_name='Max Articles to Keep'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this feed', related_name='original_feeds', to='FeedManager.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional title for the original feed', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='url',
            field=models.URLField(help_text='URL of the Atom or RSS feed', max_length=2048, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='valid',
            field=models.BooleanField(blank=True, default=None, editable=False, help_text='Whether the feed is valid.', null=True, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='case_sensitive',
            field=models.BooleanField(default=False, help_text='For filter keyword, default to unchecked for ignoring case.', verbose_name='Case Sensitive'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency of the digest.', max_length=20, verbose_name='Digest Frequency'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_model',
            field=models.CharField(choices=[('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4.5-preview', 'GPT-4.5 Preview'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='gpt-4.1-mini', help_text='Model for digest generation.', max_length=255, verbose_name='Digest Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='feed_group_relational_operator',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', help_text='The included articles must match All/Any/None of the filters.', max_length=20, verbose_name='Feed Filter Logic'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='feeds',
            field=models.ManyToManyField(help_text='All selected original feeds will be aggregated into this feed.', related_name='processed_feeds', to='FeedManager.originalfeed', verbose_name='Original Feeds'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='include_content',
            field=models.BooleanField(default=False, help_text='Include full content in digest.', verbose_name='Include Full Content'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='include_one_line_summary',
            field=models.BooleanField(default=True, help_text='Include one line summary in digest, only works for default summarization.', verbose_name='Include One Line Summary'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='include_summary',
            field=models.BooleanField(default=False, help_text='Include full summary in digest.', verbose_name='Include Full Summary'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='include_toc',
            field=models.BooleanField(default=True, help_text='Include table of contents in digest.', verbose_name='Include Table of Contents'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='last_digest',
            field=models.DateTimeField(blank=True, default=None, help_text='Last time the digest was generated, change if you want to reset the digest timer or force a new digest.', null=True, verbose_name='Last Digest'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='model',
            field=models.CharField(choices=[('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4.5-preview', 'GPT-4.5 Preview'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='gpt-4.1-mini', max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='other_digest_model',
            field=models.CharField(blank=True, default='', help_text="Please specify the OpenAI-compatible model if 'Other' is selected above, e.g. 'grok-3' in xAI.", max_length=255, verbose_name='Other Digest Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='other_model',
            field=models.CharField(blank=True, default='', help_text="Please specify the model if 'Other' is selected above, e.g. 'grok-3' in xAI.", max_length=255, verbose_name='Other Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='send_full_article',
            field=models.BooleanField(default=False, help_text='(Ignored without prompt) Send full article content for AI digest, by default only link, title, and summary are sent.', verbose_name='Send Full Article'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='summary_group_relational_operator',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', help_text='The included articles must match All/Any/None of the filters for summarization.', max_length=20, verbose_name='Summary Filter Logic'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='summary_language',
            field=models.CharField(default='English', help_text='Language for summarization, will be ignored if summarization is disabled or using custom prompt.', max_length=20, verbose_name='Summary Language'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='toggle_digest',
            field=models.BooleanField(default=False, help_text='Send a digest of the feed regularly.', verbose_name='Enable Digest'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='toggle_entries',
            field=models.BooleanField(default=True, help_text='Include entries in the feed, disable to only send digest regularly.', verbose_name='Include Entries'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='translate_title',
            field=models.BooleanField(default=False, help_text='If this option is true, Article title is translated to summary language.', verbose_name='Article Title Translation'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='use_ai_digest',
            field=models.BooleanField(default=False, help_text='Use AI to process digest content.', verbose_name='Use AI Digest'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
