# Generated by Django 5.0.6 on 2025-08-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0027_alter_appsetting_options_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='auth_code',
            field=models.CharField(blank=True, help_text='Optional authentication code to access RSS feeds', max_length=64, null=True, verbose_name='Auth Code'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='max_articles_to_keep',
            field=models.PositiveIntegerField(default=1000, help_text='Older articles will be removed when limit is reached', verbose_name='Max Articles to Keep'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='original_feeds', to='FeedManager.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Display name for this feed', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='url',
            field=models.URLField(help_text='RSS or Atom feed URL', max_length=2048, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='originalfeed',
            name='valid',
            field=models.BooleanField(blank=True, default=None, editable=False, null=True, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='additional_prompt',
            field=models.TextField(blank=True, default='', help_text='Override default summarization prompt. Can be used for translation or custom instructions', verbose_name='Custom Prompt'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='additional_prompt_for_digest',
            field=models.TextField(blank=True, default='', help_text='Custom prompt for AI digest generation. Without this, only title, link and summary are included', verbose_name='Digest Prompt'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='articles_to_summarize_per_interval',
            field=models.PositiveIntegerField(default=0, help_text='Number of articles to summarize per update. All articles included in feed, set to 0 to disable summarization', verbose_name='Articles to summarize per update'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='case_sensitive',
            field=models.BooleanField(default=False, help_text='Enable case-sensitive filter matching. Default is case-insensitive', verbose_name='Case Sensitive'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20, verbose_name='Digest Frequency'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_model',
            field=models.CharField(choices=[('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4.5-preview', 'GPT-4.5 Preview'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='gpt-4.1-mini', max_length=255, verbose_name='Digest Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='feed_group_relational_operator',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', help_text='Articles must match All/Any/None of the filters to be included', max_length=20, verbose_name='Feed Filter Logic'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='feeds',
            field=models.ManyToManyField(help_text='Original feeds to aggregate into this processed feed', related_name='processed_feeds', to='FeedManager.originalfeed', verbose_name='Original Feeds'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='include_content',
            field=models.BooleanField(default=False, verbose_name='Include Full Content'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='include_one_line_summary',
            field=models.BooleanField(default=True, help_text='Only works with default summarization (no custom prompt)', verbose_name='Include One Line Summary'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='include_summary',
            field=models.BooleanField(default=False, verbose_name='Include Full Summary'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='include_toc',
            field=models.BooleanField(default=True, verbose_name='Include Table of Contents'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='last_digest',
            field=models.DateTimeField(blank=True, default=None, help_text='Last digest generation time. Modify to reset timer or force new digest', null=True, verbose_name='Last Digest'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='other_digest_model',
            field=models.CharField(blank=True, default='', help_text="Specify OpenAI-compatible model if 'Other' is selected above, e.g. 'grok-3' in xAI", max_length=255, verbose_name='Other Digest Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='other_model',
            field=models.CharField(blank=True, default='', help_text="Specify model name if 'Other' is selected above, e.g. 'grok-3' in xAI", max_length=255, verbose_name='Other Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='send_full_article',
            field=models.BooleanField(default=False, help_text='Send full article content to AI. Ignored without digest prompt. Default sends only link, title, and summary', verbose_name='Send Full Article'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='summary_group_relational_operator',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', help_text='Articles must match All/Any/None of the filters to be summarized', max_length=20, verbose_name='Summary Filter Logic'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='summary_language',
            field=models.CharField(default='English', help_text='Target language for summarization. Ignored if using custom prompt', max_length=20, verbose_name='Summary Language'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='toggle_digest',
            field=models.BooleanField(default=False, help_text='Generate periodic digest of the feed', verbose_name='Enable Digest'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='toggle_entries',
            field=models.BooleanField(default=True, help_text='Include individual entries in feed. Disable to only generate digest', verbose_name='Include Entries'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='translate_title',
            field=models.BooleanField(default=False, help_text='Translate article titles to summary language', verbose_name='Article Title Translation'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='use_ai_digest',
            field=models.BooleanField(default=False, verbose_name='Use AI Digest'),
        ),
    ]
