# Generated by Django 5.0.6 on 2025-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0028_alter_appsetting_auth_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfeed',
            name='feed_group_relational_operator',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', help_text='Logic between filter groups for feed inclusion: match All/Any/None of the filter groups', max_length=20, verbose_name='Logic Between Feed Filter Groups'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='summary_group_relational_operator',
            field=models.CharField(choices=[('all', 'All'), ('any', 'Any'), ('none', 'None')], default='any', help_text='Logic between filter groups for summarization: match All/Any/None of the filter groups', max_length=20, verbose_name='Logic Between Summary Filter Groups'),
        ),
    ]
