# Generated by Django 5.0.6 on 2025-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0029_alter_processedfeed_feed_group_relational_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_model',
            field=models.CharField(choices=[('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='gpt-4.1-mini', max_length=255, verbose_name='Digest Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='model',
            field=models.CharField(choices=[('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='gpt-4.1-mini', max_length=255, verbose_name='Model'),
        ),
    ]
