# Generated by Django 5.0.6 on 2025-08-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0030_alter_processedfeed_digest_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='global_digest_model',
            field=models.CharField(choices=[('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='gpt-4.1-mini', help_text='Default AI model for digest generation across all feeds', max_length=255, verbose_name='Global Digest Model'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='global_other_digest_model',
            field=models.CharField(blank=True, default='', help_text="Specify model name if 'Other' is selected above, e.g. 'grok-3' in xAI", max_length=255, verbose_name='Global Other Digest Model'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='global_other_summary_model',
            field=models.CharField(blank=True, default='', help_text="Specify model name if 'Other' is selected above, e.g. 'grok-3' in xAI", max_length=255, verbose_name='Global Other Summary Model'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='global_summary_model',
            field=models.CharField(choices=[('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='gpt-4.1-mini', help_text='Default AI model for article summarization across all feeds', max_length=255, verbose_name='Global Summary Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_model',
            field=models.CharField(choices=[('use_global', 'Use Global Setting'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='use_global', max_length=255, verbose_name='Digest Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='model',
            field=models.CharField(choices=[('use_global', 'Use Global Setting'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='use_global', max_length=255, verbose_name='Model'),
        ),
    ]
