# Generated by Django 5.0.6 on 2025-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0031_appsetting_global_digest_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='global_digest_model',
            field=models.CharField(choices=[('none', 'None - Disable AI Features Globally'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='none', help_text="Master switch for AI digest generation. When set to 'None', ALL AI digests are disabled system-wide, regardless of individual feed settings. When set to a model, it enables AI features and serves as the default for feeds using 'Use Global Setting'.", max_length=255, verbose_name='Global Digest Model'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='global_summary_model',
            field=models.CharField(choices=[('none', 'None - Disable AI Features Globally'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='none', help_text="Master switch for AI summarization. When set to 'None', ALL AI summaries are disabled system-wide, regardless of individual feed settings. When set to a model, it enables AI features and serves as the default for feeds using 'Use Global Setting'.", max_length=255, verbose_name='Global Summary Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_model',
            field=models.CharField(choices=[('use_global', 'Use Global Setting'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='use_global', help_text="AI model for digest generation. Note: Requires global AI to be enabled in App Settings. If global AI is disabled (set to 'None'), this setting will have no effect.", max_length=255, verbose_name='Digest Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='model',
            field=models.CharField(choices=[('use_global', 'Use Global Setting'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='use_global', help_text="AI model for summarization. Note: Requires global AI to be enabled in App Settings. If global AI is disabled (set to 'None'), this setting will have no effect.", max_length=255, verbose_name='Summary Model'),
        ),
    ]
