# Generated by Django 5.0.6 on 2025-08-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0032_alter_appsetting_global_digest_model_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_date'], name='article_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['summarized'], name='article_summarized_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['original_feed', '-published_date'], name='article_feed_date_idx'),
        ),
        migrations.AddIndex(
            model_name='processedfeed',
            index=models.Index(fields=['name'], name='feed_name_idx'),
        ),
        migrations.AddIndex(
            model_name='processedfeed',
            index=models.Index(fields=['-last_modified'], name='feed_modified_idx'),
        ),
    ]
