# Generated by Django 5.0.6 on 2025-08-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0033_article_article_pub_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalfeed',
            name='max_articles_to_keep',
            field=models.PositiveIntegerField(default=500, help_text='Older articles will be removed when limit is reached', verbose_name='Max Articles to Keep'),
        ),
    ]
