# Generated by Django 5.0.6 on 2025-08-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0034_alter_originalfeed_max_articles_to_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='max_articles_per_feed',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of articles to include in each processed feed. This limit helps improve performance by reducing database queries and filter processing time. Articles are sorted by publication date (newest first).', verbose_name='Max Articles Per Processed Feed'),
        ),
    ]
