# Generated by Django 5.0.6 on 2025-08-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0035_appsetting_max_articles_per_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='global_digest_model',
            field=models.CharField(choices=[('none', 'None - Disable AI Features Globally'), ('gpt-5-mini', 'GPT-5 Mini'), ('gpt-5-nano', 'GPT-5 Nano'), ('gpt-5', 'GPT-5'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1', 'GPT-4.1'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('other', 'Other (specify below)')], default='none', max_length=255, verbose_name='Global Digest Model'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='global_other_digest_model',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Global Other Digest Model'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='max_articles_per_feed',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of articles to include in each processed feed (does not affect the number of articles in the original feeds stored in database). Articles are sorted by publication date (newest first).', verbose_name='Max Articles Per Processed Feed'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='send_full_article',
            field=models.BooleanField(default=False, help_text='Send FULL content of ALL articles during since last digest to AI for digest, in addtion to the default title, link, and summaries.', verbose_name='Send Full Article'),
        ),
    ]
