# Generated by Django 5.0.6 on 2025-09-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0036_alter_appsetting_global_digest_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='processedfeed',
            name='include_tags',
            field=models.ManyToManyField(blank=True, help_text='Automatically include all original feeds that have any of these tags', related_name='processed_feeds', to='FeedManager.tag', verbose_name='Include Tags'),
        ),
    ]
