# Generated by Django 5.0.6 on 2025-09-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0037_alter_tag_options_processedfeed_include_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfeed',
            name='feeds',
            field=models.ManyToManyField(blank=True, help_text='Original feeds to aggregate into this processed feed', related_name='processed_feeds', to='FeedManager.originalfeed', verbose_name='Original Feeds'),
        ),
    ]
