# Generated by Django 5.2.16 on 2026-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0038_alter_processedfeed_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='user_agent',
            field=models.CharField(blank=True, default='', help_text="User-Agent header used when fetching feeds. Leave empty to use a random browser User-Agent (default). Set a fixed value if a feed blocks unknown or rotating user agents, e.g. 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'.", max_length=512, verbose_name='Global User-Agent'),
        ),
        migrations.AddField(
            model_name='originalfeed',
            name='user_agent',
            field=models.CharField(blank=True, default='', help_text="Overrides the global User-Agent from App Settings for this feed only. Leave empty to use the global setting. Enter 'random' to force a random browser User-Agent for this feed.", max_length=512, verbose_name='User-Agent'),
        ),
    ]
