# Generated by Django 5.0.6 on 2026-08-25 09:29

import FeedManager.model_registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedManager', '0039_appsetting_user_agent_originalfeed_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='global_digest_model',
            field=models.CharField(choices=FeedManager.model_registry.get_global_model_choices, default='none', max_length=255, verbose_name='Global Digest Model'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='global_summary_model',
            field=models.CharField(choices=FeedManager.model_registry.get_global_model_choices, default='none', help_text="Master switch for AI summarization. When set to 'None', ALL AI summaries are disabled system-wide, regardless of individual feed settings. When set to a model, it enables AI features and serves as the default for feeds using 'Use Global Setting'.", max_length=255, verbose_name='Global Summary Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='digest_model',
            field=models.CharField(choices=FeedManager.model_registry.get_model_choices, default='use_global', help_text="AI model for digest generation. Note: Requires global AI to be enabled in App Settings. If global AI is disabled (set to 'None'), this setting will have no effect.", max_length=255, verbose_name='Digest Model'),
        ),
        migrations.AlterField(
            model_name='processedfeed',
            name='model',
            field=models.CharField(choices=FeedManager.model_registry.get_model_choices, default='use_global', help_text="AI model for summarization. Note: Requires global AI to be enabled in App Settings. If global AI is disabled (set to 'None'), this setting will have no effect.", max_length=255, verbose_name='Summary Model'),
        ),
    ]
